### ISSUE TITLE
Support sqlite vector search module

### ISSUE THREAD

**Issue by bjsi** [lgrammel/modelfusion#157]
There's a sqlite extension to support vector search called [sqlite-vss](https://github.com/asg017/sqlite-vss). This would be a welcome addition to modelfusion because sqlite is like a stepping stone between the in-memory JSON vector DB and a "proper" vector DB like pinecone. The advantage it has over the in-memory JSON approach is that it doesn't take up a bunch of RAM, so I can deploy prototypes quickly for free without upgrading to paid tiers 😄. Also it's less setup than pinecone.

I would be glad to implement this myself because I'm already familiar with sqlite-vss if that sounds good to you.

**Comment by lgrammel** [comment]
@bjsi awesome idea! there are some existing example (in-memory vector db, pinecone). Ideally this would be a separate extension, similar to `extensions/pinecone`. Let me know if you have any questions :)

**Comment by bjsi** [comment]
Great! I'll have a go and let you know if I run into any issues :)
