### ISSUE TITLE
First parameter has member `readable` when running generate text on AWS Lambda.

### ISSUE THREAD

**Issue by Morphexe** [lgrammel/modelfusion#263]
Hey, I was trying to get modefusion to work on a lambda and I got hit by this error:

```
TypeError: First parameter has member 'readable' that is not a ReadableStream.
```

This happens when I try to run the following inside a lambda:

```
    const run = new DefaultRun();
    const result = await generateText({
      model: openai.ChatTextGenerator({
        model: 'gpt-4-vision-preview',
        temperature: 0,
        maxGenerationTokens: 2500,
      }),
      prompt,
      fullResponse: true,
      run,
    }).catch((err) => {
      console.error('Error generating text', err);
      return null;
    });
```
    
As soon as it hits the await it crashes the lambda with that error message, I cant seem to find a solution/pointer online, but maybe someone here has hit something similar to this?
   
 I have tried both Node18 and Node20 runtimes - just in case. Do you have any ideas what might be occuring?
 
 P.S this seems to have started happening quite recently for me when I updated to latest version of `modelfusion`.
 
 Any help is appreciated!

**Comment by lgrammel** [comment]
@Morphexe tried to reproduce it locally (without AWS lambda) and noticed that you attached a catch to the generate text.

The following worked for me:
```
import dotenv from "dotenv";
import {
  DefaultRun,
  OpenAIChatPrompt,
  generateText,
  openai,
} from "modelfusion";

dotenv.config();

async function myFunction(prompt: OpenAIChatPrompt) {
  try {
    const run = new DefaultRun();
    return await generateText({
      model: openai.ChatTextGenerator({
        model: "gpt-4-vision-preview",
        temperature: 0,
        maxGenerationTokens: 2500,
      }),
      prompt,
      fullResponse: true,
      run,
    });
  } catch (err) {
    console.error("Error generating text", err);
    return null;
  }
}

async function main() {
  console.log(
    await myFunction([
      {
        role: "user",
        content: "print something",
      },
    ])
  );
}

main().catch(console.error);
```
Can you see if it's related to how you perform the catch (i.e., change it into a try..catch around the awaited statement)?

**Comment by Morphexe** [comment]
This seems to have been caused by a recent update somehow, but I also seems to not be `modelfusion` specific, but seems to be more a bundling issue on my side, which was pulled forward by something in latestest `modelfusion`.

Initial debugging today , threw me in the `web-stream-pollyfill`  based on some other issues I found  while searching online. 

So apologies, this might not be something you need to solve, literally bad timing since I updated the lib and this started happening, so I might have pulled the trigger in thinking it was related `modelfusion`.

**Comment by lgrammel** [comment]
No worries. I'll close this issue for now. Please re-open if you discover it's related to ModelFusion. Thanks!
