### ISSUE TITLE
experimental-vm-modules bug introduced in v0.134.0

### ISSUE THREAD

**Issue by jakedetels** [lgrammel/modelfusion#278]
I updated to the latest version of Model Fusion (0.135.0) and found that my previously passing tests were now failing with this error:

```shell
    TypeError: A dynamic import callback was invoked without --experimental-vm-modules

      at ensureLoaded (node_modules/src/core/getRun.ts:14:35)
      at getRun (node_modules/src/core/getRun.ts:25:9)
      at executeStandardCall (node_modules/src/model-function/executeStandardCall.ts:42:21)
      at generateText (node_modules/src/model-function/generate-text/generateText.ts:77:30)
```

I've tested in the latest version of node.js and the LTS, and a few recent older versions: same results each time.

I isolated the error to be something that was introduced in v0.134.0 (as the same test suite passes up until v0.133.0).  I tried examining the Model Fusion diffs between those two versions (https://github.com/lgrammel/modelfusion//compare/v0.133.0...v0.134.0#), but I couldn't identify the source of the issue.

Please advise.  I didn't see anything in the release notes indicating breaking changes in v0.134.0.  Thanks in advance.

**Comment by lgrammel** [comment]
Thanks for the bug report. I suspect it is because I switched bundling to tsup. Can you share some code that can help me reproduce the issue?

**Comment by lgrammel** [comment]
@jakedetels I did some digging and it might be related to jest specifically (see https://jestjs.io/docs/ecmascript-modules ). Are you using jest by any chance? Does this also happen outside of tests?

**Comment by lgrammel** [comment]
@jakedetels can you try https://github.com/lgrammel/modelfusion/releases/tag/v0.135.1 ?

It should fix the issue. If you still run into it, please re-open.

**Comment by jakedetels** [comment]
@lgrammel, thanks for the quick attention on this.  I tested with 0.135.1, and confirm that it fixed the previously reported issue and my tests are now passing again.  However, the patch release introduced a bug/side effect related to the schema of the event objects that are emitted (which I leverage for logging purposes).  In 133, `event.input` was an array of messages (see first screenshot). Now in 0.135.1, to access the same array that was at `event.input` earlier, code must be revised as `event.input.input` (see second screenshot).  How do you advise proceeding?  Is the new event object schema locked in, or will you restore to the pre-v0.135.1 version? 

0.133.0
<img width="440" alt="image" src="https://github.com/lgrammel/modelfusion/assets/8092406/f73d1163-b0e4-47c8-9efe-29feecf76f3e">


0.135.1 
<img width="440" alt="image" src="https://github.com/lgrammel/modelfusion/assets/8092406/3efb2921-2c3c-4ba0-aee4-069c386fad17">

**Comment by lgrammel** [comment]
> @lgrammel, thanks for the quick attention on this. I tested with 0.135.1, and confirm that it fixed the previously reported issue and my tests are now passing again. However, the patch release introduced a bug/side effect related to the schema of the event objects that are emitted (which I leverage for logging purposes). In 133, `event.input` was an array of messages (see first screenshot). Now in 0.135.1, to access the same array that was at `event.input` earlier, code must be revised as `event.input.input` (see second screenshot). How do you advise proceeding? Is the new event object schema locked in, or will you restore to the pre-v0.135.1 version?
> 
> 0.133.0 <img alt="image" width="440" src="https://private-user-images.githubusercontent.com/8092406/302131854-f73d1163-b0e4-47c8-9efe-29feecf76f3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjQ1MTksIm5iZiI6MTcwNzEyNDIxOSwicGF0aCI6Ii84MDkyNDA2LzMwMjEzMTg1NC1mNzNkMTE2My1iMGU0LTQ3YzgtOWVmZS0yOWZlZWNmNzZmM2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDkxMDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWQ2NGFjYTIzZWQ5NzlkZjAxYTIyOTEyNjViYTczYTNhZjE3MDVlMTlmMWZjYWU5MmRkZGQwNzViMzdmOGE3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.opg1SICGs3ILnmbv4tN_tO63xk7V38qJiFWWD_0z6DY">
> 
> 0.135.1 <img alt="image" width="440" src="https://private-user-images.githubusercontent.com/8092406/302131749-3efb2921-2c3c-4ba0-aee4-069c386fad17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjQ1MTksIm5iZiI6MTcwNzEyNDIxOSwicGF0aCI6Ii84MDkyNDA2LzMwMjEzMTc0OS0zZWZiMjkyMS0yYzNjLTRiYTAtYWVlNC0wNjljMzg2ZmFkMTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDkxMDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWZlMzI0YzdhZGI2Y2I2NjRhNGJjODdhZjM4MzYxZWJlNzBmZjc5ZmRhMzU0OWExNTIyZjhjYWNlMTEzYTcwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._NwO8x3O96fLHlAhn_-IZbvDCX-KkOhIE7TGzMV8mUo">

@jakedetels this is expected (a result of introducing prompt functions). In general, the event structure is an area that will likely change a bit more going forward. Are you using the events / input information or is this caused by snapshot tests?

**Comment by jakedetels** [comment]
@lgrammel, I've been using the event object within a logging service I'm using. (Issue is unrelated to snapshot testing.)  No worries if the event schema will change a bit further, but it would be nice to lock things in at some point soon, since the event object is part of MF's public API for function observers.

**Comment by lgrammel** [comment]
@jakedetels totally - it's good to know that you are using the event, so I'll keep that in mind when there are updates.
