### ISSUE TITLE
PDF to Tweet - error

### ISSUE THREAD

**Issue by andreasdevjs** [lgrammel/modelfusion#93]
Generate text rewrite-tweet text-generation.
Generate text rewrite-tweet text-generation.
TypeError: responses is not iterable
    at calculateOpenAIEmbeddingCostInMillicents
    

how can i solve this?

**Comment by lgrammel** [comment]
Thanks for reporting the bug. The example seems to be broken. I'll look into it.

**Comment by lgrammel** [comment]
I have fixed the issue in `v0.30.1` and also updated the example. Please re-open this ticket if you still see it happening.

**Comment by andreasdevjs** [comment]
hey, thanks for the quick reply.. maybe im doing something wrong but i still get this:

Generate text rewrite-tweet text-generation.
Generate text rewrite-tweet text-generation.

TypeError: responses is not iterable
    at calculateOpenAIEmbeddingCostInMillicents 
    node_modules/modelfusion/model-provider/openai/OpenAITextEmbeddingModel.cjs:26:28)
    at OpenAICostCalculator.calculateCostInMillicents
     /node_modules/modelfusion/model-provider/openai/OpenAICostCalculator.cjs:32:103)
    at calculateCost

**Comment by lgrammel** [comment]
Hm can you confirm that you are using ModelFusion `v0.30.1`? This was caused by a single object (instead of an array) being sent into the cost calculation.

If that does not solve it, can you log `run.successfulModelCalls` to the console before `calculateCost` is called. The `text-embedding-ada-002` entries should look like this:

```
  {
    model: { provider: 'openai', modelName: 'text-embedding-ada-002' },
    settings: {},
    response: [ [Object] ],
    type: 'text-embedding'
  },
  ```

**Comment by andreasdevjs** [comment]
Thanks!! now is solved, was the version 🙌🏽
